version: '3'
services:
  mock:
    image: "stoplight/prism:latest"
    command: 'mock -h 0.0.0.0 /app/apispec.yml'
    ports: 
      - "4010:4010"
    volumes: 
      - ./:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4010/"]
      interval: 200s
      timeout: 200s
      retries: 5  