name: API Test

on: workflow_dispatch

jobs:
  Linux:
    name: Validate API spec
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 3.5.0
      - name: Lint
        run: inso lint spec "spc_cfd3cb71496d467299baefae57008bfe" --ci
      - name: Export the apispec
        run: inso export spec spc_cfd3cb71496d467299baefae57008bfe > apispec.yml 
      - name: Start the Containers
        run: docker-compose -f "docker-compose.yml" up -d
      - name: Connect to the Docker Network
        run: docker ps -a 
      - name: validate mock is up
        run: docker logs insomnia-helloworld_mock_1
      - name: Run test suites
        run: inso run test "spc_cfd3cb71496d467299baefae57008bfe" --env UnitTest --ci
      - name: Generate declarative config
        run: inso generate config "spc_cfd3cb71496d467299baefae57008bfe" --type declarative --ci -o disputes_deck.yaml
