name: API Test

on: workflow_dispatch

jobs:
  Linux:
    name: Validate API spec
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - uses: kong/setup-inso@v1
        with:
          inso-version: 3.5.0
      - name: Lint
        run: | 
          echo testing inso lint
           inso lint spec "spc_cfd3cb71496d467299baefae57008bfe" --ci
      - name: Export the apispec
        run: inso export spec spc_cfd3cb71496d467299baefae57008bfe > apispec.yml 
      - name: Start the Containers
        run: docker-compose -f "docker-compose.yml" up -d
      - name: Wait for Mock Container to be ready
        run: |
          chmod a+x ./wait-for-it.sh
          ./wait-for-it.sh localhost:4010 -t 10 -- echo "Mocker is up"
          sleep 10
          curl -X GET http://localhost:4010/
      - name: Validate Connection
        run: curl -X GET http://localhost:4010/
      - name: Run test suites
        run: inso run test "spc_cfd3cb71496d467299baefae57008bfe" --env UnitTest --ci
      - name: Generate declarative config
        run: inso generate config "spc_cfd3cb71496d467299baefae57008bfe" --type declarative --ci -o disputes_deck.yml
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          file_pattern: 'disputes_deck.yml apispec.yml'
          commit_message: "Automated - Create Disputes Deck"
