name: API Test

on: 
  workflow_dispatch:
    inputs: 
      version:
        description: "New API Ops Version"
        required: true
        type: string
        default: 1.0.0
jobs:
  test:
    name: Validate API spec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - uses: kong/setup-inso@v1
        with:
          inso-version: 3.5.0
      - name: Lint
        run: | 
          echo testing inso lint
           inso lint spec "spc_cfd3cb71496d467299baefae57008bfe" --ci
      - name: Export the apispec
        run: inso export spec spc_cfd3cb71496d467299baefae57008bfe > apispec.yml 
      - name: Start the Containers
        run: docker-compose -f "docker-compose.yml" up -d
      - name: Wait for Mock Container to be ready
        run: |
          chmod a+x ./wait-for-it.sh
          ./wait-for-it.sh localhost:4010 -t 10 -- echo "Mocker is up"
          sleep 10
          curl -X GET http://localhost:4010/
      - name: Validate Connection
        run: curl -X GET http://localhost:4010/
      - name: Run test suites
        run: inso run test "spc_cfd3cb71496d467299baefae57008bfe" --env UnitTest --ci
      - name: Generate declarative config
        run: inso generate config "spc_cfd3cb71496d467299baefae57008bfe" --type declarative --ci -o disputes_deck.yml
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          file_pattern: 'disputes_deck.yml apispec.yml'
          commit_message: "Automated - Create Disputes Deck"

  create-gateway-pr:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with: 
          repository: DaniellaFreese/insomnia-helloworld
          path: disputes
          fetch-depth: 0
      - name: Checkout API Gateway Repo
        uses: actions/checkout@v2
        with:
          repository: DaniellaFreese/apiops-gateway
          ref: dev
          path: apiops
          fetch-depth: 0
          token: ${{ secrets.APIOPS_PAT }}
      - name: Setup Git Config 
        run: |
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "github-actions"

      - name: Copy content over and create a branch
        run: | 
          cp disputes/apispec.yml apiops/disputes/apispec.yml
          cp disputes/disputes_dec.yml apiops/disputes/disputes_deck.yml
      
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: apiops
          branch: disputes-v${{ inputs.version }}
          file_pattern: 'disputes_deck.yml apispec.yml'
          commit_message: "Disputes APISpec and Deck"
          create_branch: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with: 
          commit-message: 'disputes apispec and deck conf'

